-- Product Dimension Table
CREATE TABLE IF NOT EXISTS {{ database_name }}.{{ sf_schema }}.PRODUCT (
    PRODUCT_ID NUMBER(10,0) NOT NULL PRIMARY KEY,
    PRODUCT_NAME VARCHAR(255) NOT NULL,
    CATEGORY VARCHAR(100),
    SUBCATEGORY VARCHAR(100),
    BRAND VARCHAR(100),
    UNIT_PRICE NUMBER(12,2) NOT NULL,
    COST_PRICE NUMBER(12,2),
    SUPPLIER_ID NUMBER(10,0),
    SKU VARCHAR(50) UNIQUE,
    DESCRIPTION VARCHAR(1000),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    IS_ACTIVE BOOLEAN DEFAULT TRUE
);

-- ============================================================================
-- FACT TABLES
-- ============================================================================

-- Order Fact Table
CREATE TABLE IF NOT EXISTS {{ database_name }}.{{ sf_schema }}.ORDER (
    ORDER_ID NUMBER(15,0) NOT NULL PRIMARY KEY,
    CUSTOMER_ID NUMBER(10,0) NOT NULL,
    ORDER_DATE DATE NOT NULL,
    ORDER_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    DELIVERY_DATE DATE,
    ORDER_STATUS VARCHAR(50),
    TOTAL_AMOUNT NUMBER(15,2) NOT NULL,
    TAX_AMOUNT NUMBER(15,2),
    DISCOUNT_AMOUNT NUMBER(15,2),
    SHIPPING_AMOUNT NUMBER(15,2),
    NET_AMOUNT NUMBER(15,2) NOT NULL,
    PAYMENT_METHOD VARCHAR(50),
    PAYMENT_STATUS VARCHAR(50),
    SHIPPING_ADDRESS VARCHAR(500),
    NOTES VARCHAR(1000),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
