-- ============================================================================
-- Snowflake DDL: Domain Tables (Order, Customer, Product) with Views
-- ============================================================================
-- Database and Schema Setup
-- ============================================================================

-- ============================================================================
-- DIMENSION TABLES
-- ============================================================================

-- Customer Dimension Table
CREATE TABLE IF NOT EXISTS {{ database_name }}.{{ sf_schema }}.CUSTOMER (
    CUSTOMER_ID NUMBER(10,0) NOT NULL PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255),
    PHONE VARCHAR(20),
    COUNTRY VARCHAR(100),
    STATE VARCHAR(100),
    CITY VARCHAR(100),
    ZIP_CODE VARCHAR(20),
    CUSTOMER_SEGMENT VARCHAR(50),
    REGISTRATION_DATE DATE,
    LAST_PURCHASE_DATE DATE,
    TOTAL_LIFETIME_VALUE NUMBER(15,2),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    IS_ACTIVE BOOLEAN DEFAULT TRUE
);

-- Product Dimension Table
CREATE TABLE IF NOT EXISTS {{ database_name }}.{{ sf_schema }}.PRODUCT (
    PRODUCT_ID NUMBER(10,0) NOT NULL PRIMARY KEY,
    PRODUCT_NAME VARCHAR(255) NOT NULL,
    CATEGORY VARCHAR(100),
    SUBCATEGORY VARCHAR(100),
    BRAND VARCHAR(100),
    UNIT_PRICE NUMBER(12,2) NOT NULL,
    COST_PRICE NUMBER(12,2),
    SUPPLIER_ID NUMBER(10,0),
    SKU VARCHAR(50) UNIQUE,
    DESCRIPTION VARCHAR(1000),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    IS_ACTIVE BOOLEAN DEFAULT TRUE
)
COMMENT = 'Product dimension table - contains product master data'
CLUSTER BY (CATEGORY, SUBCATEGORY);

-- ============================================================================
-- FACT TABLES
-- ============================================================================

-- Order Fact Table
CREATE TABLE IF NOT EXISTS {{ database_name }}.{{ sf_schema }}.ORDERS (
    ORDER_ID NUMBER(15,0) NOT NULL PRIMARY KEY,
    CUSTOMER_ID NUMBER(10,0) NOT NULL,
    ORDER_DATE DATE NOT NULL,
    ORDER_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    DELIVERY_DATE DATE,
    ORDER_STATUS VARCHAR(50),
    TOTAL_AMOUNT NUMBER(15,2) NOT NULL,
    TAX_AMOUNT NUMBER(15,2),
    DISCOUNT_AMOUNT NUMBER(15,2),
    SHIPPING_AMOUNT NUMBER(15,2),
    NET_AMOUNT NUMBER(15,2) NOT NULL,
    PAYMENT_METHOD VARCHAR(50),
    PAYMENT_STATUS VARCHAR(50),
    SHIPPING_ADDRESS VARCHAR(500),
    NOTES VARCHAR(1000),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Order Line Items Table
CREATE TABLE IF NOT EXISTS {{ database_name }}.{{ sf_schema }}.ORDERS_LINE_ITEM (
    LINE_ITEM_ID NUMBER(15,0) NOT NULL PRIMARY KEY,
    ORDER_ID NUMBER(15,0) NOT NULL,
    PRODUCT_ID NUMBER(10,0) NOT NULL,
    QUANTITY NUMBER(10,2) NOT NULL,
    UNIT_PRICE NUMBER(12,2) NOT NULL,
    LINE_TOTAL NUMBER(15,2) NOT NULL,
    DISCOUNT_PERCENT NUMBER(5,2),
    DISCOUNT_AMOUNT NUMBER(15,2),
    NET_LINE_AMOUNT NUMBER(15,2),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
